### ISSUE TITLE
Segfault in ast_format_cap_append_from_cap

### ISSUE THREAD

**Issue by pnlarsson** [marcelloceschia/chan-sccp-b#550]
Segfault with latest develop branch:

[2020-12-18 09:24:23] VERBOSE[15594][C-0000004e] app_dial.c: PJSIP/ngcore-00005786 is making progress passing it to SCCP/wid19985-00000174
[2020-12-18 09:24:37] Asterisk 13.38.0 built by root @ uc168 on a x86_64 running Linux on 2020-12-15 22:09:31 UTC

**chan-sccp version:** Skinny Client Control Protocol (SCCP). Release: 4.3.2 (HEAD - 76000de (built by 'root' on '2020-12-15 22:18:34 UTC')

**asterisk version:** Asterisk 13.38.0 built by root @ uc168 on a x86_64 running Linux on 2020-12-15 22:09:31 UTC

**Addition / Optional Information:**
- Problem started happening recently, didn't happen in an older version of Chan-SCCP: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [No]
- Platform:
  - Debian 10 x86_64

Backtrace (full bt availible):
```[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/ngcore/service/pbx/sbin/asterisk -f -F -g -C /usr/local/ngcore/servi'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056055f1a111b in ast_format_cap_append_from_cap (dst=0x7f532007d870, src=0x7f5320172e70, type=AST_MEDIA_TYPE_AUDIO) at format_cap.c:311
311			struct format_cap_framed *framed = AST_VECTOR_GET(&src->preference_order, idx);
[Current thread is 1 (Thread 0x7f511b289700 (LWP 15594))]
#0  0x000056055f1a111b in ast_format_cap_append_from_cap (dst=0x7f532007d870, src=0x7f5320172e70, type=AST_MEDIA_TYPE_AUDIO) at format_cap.c:311
        __idx = 0
        framed = 0x7f529c011d60
        idx = 0
        res = 0
#1  0x00007f539fa27a20 in __find_joint_capabilities (c=c@entry=0x7f529c0153f0, peer=peer@entry=0x7f532006cd48, media_type=media_type@entry=AST_MEDIA_TYPE_AUDIO, remoteCapabilities=remoteCapabilities@entry=0x7f529c015718) at ast113.c:463
        buf = "\260\033\002\234R\177\000\000\020X\243\237S\177\000\000\260\033\002\234R\177\000\000\000\032Vt)\240~\342\240\063(\033Q\177\000\000\240\063(\033Q\177\000\000\377\000\000\000\000\000\000\000\223\006-_\005V\000\000H5(\033Q\177\000\000 \335\066_\005V\000\000\310J\002 S\177\000\000\240ǁCT\177\000\000\001\200\255\373Q\177\000\000\310J\002 S\177\000\000\067g\334_\000\000\000\000\243.\a\000\000\000\000\000\027\000\000\000\030\000\000\000\t\000\000\000\022\000\000\000\v\000\000\000x\000\000\000\005\000\000\000`\001\000\000\000\000\000\000\000\000\000\000 \200B\324R\177\000\000\000\000\000\000\000\000\000\000\243.\a", '\000' <repeats 13 times>, "\220"...
        codec_buf = 0x7f511b283290
        owner = 0x7f529c023258
        caps = 0x7f529c01b0b0
        payload_caps = 0x7f5320174080
        remote_caps = 0x7f532007d870
        joint = 0x7f5320002fe0
        best_fmt_cap = 0x0
        best_fmt_native = 0x0
        __PRETTY_FUNCTION__ = "__find_joint_capabilities"
#2  0x00007f539fa28498 in pbx_retrieve_remote_capabilities (c=0x7f529c0153f0) at ast113.c:555
        codec_buf = 0x7f511b283590
        __PRETTY_FUNCTION__ = "pbx_retrieve_remote_capabilities"
        ast = 0x7f529c023258
        remotePeer = 0x7f532006cd48
        iterator = 0x7f5320000960
#3  0x00007f539fa29dae in sccp_astwrap_indicate (ast=0x7f529c023258, ind=14, data=0x0, datalen=0) at ast113.c:676
        res = 0
        c = 0x7f529c0153f0
        ref0 = {ptr = 0x7f511b283650, file = 0x7f539fa66b5f "ast113.c", func = 0x7f539fa63ad0 <__PRETTY_FUNCTION__.24754> "sccp_astwrap_indicate", line = 614}
        __PRETTY_FUNCTION__ = "sccp_astwrap_indicate"
        d = 0x7f529c006e60
        ref1 = {ptr = 0x7f511b283658, file = 0x7f539fa66b5f "ast113.c", func = 0x7f539fa63ad0 <__PRETTY_FUNCTION__.24754> "sccp_astwrap_indicate", line = 621}
        inband_if_receivechannel = false
#4  0x000056055f131aa3 in indicate_data_internal (chan=0x7f529c023258, _condition=14, data=0x0, datalen=0) at channel.c:4782
        condition = AST_CONTROL_PROGRESS
        ts = 0x0
        t38_parameters = 0x7f529c023220
        res = 22021
        __PRETTY_FUNCTION__ = "indicate_data_internal"
#5  0x000056055f131f67 in ast_indicate_data (chan=0x7f529c023258, _condition=14, data=0x0, datalen=0) at channel.c:4948
        res = 32595
        awesome_frame = 0x0
        __PRETTY_FUNCTION__ = "ast_indicate_data"
#6  0x000056055f13139b in ast_indicate (chan=0x7f529c023258, condition=14) at channel.c:4538
No locals.
#7  0x00007f54300bf0c8 in wait_for_answer (in=0x7f529c023258, out_chans=0x7f511b285550, to=0x7f511b28554c, peerflags=0x7f511b2858b8, opt_args=0x7f511b284d90, pa=0x7f511b284e70, num_in=0x7f511b285530, result=0x7f511b284e6c, dtmf_progress=0x0, ignore_cc=0, forced_clid=0x7f511b284c40, stored_clid=0x7f511b284bf0) at app_dial.c:1535
        f = 0x7f51940635e0
        c = 0x7f532006cd48
        o = 0x7f5320077a50
        pos = 2
        numlines = 1
        winner = 0x7f532006cd48
        watchers = {0x7f529c023258, 0x7f532006cd48, 0x0, 0x0, 0x20, 0x7f511b283e68, 0x0, 0x0, 0x0, 0x7f544395b760 <_IO_helper_jumps>, 0xd68, 0x56055f2d0693, 0x0, 0x56055f2d0693, 0x1, 0x56055f2d0695, 0x0, 0x7f511b283fb0, 0x7f511b283fa0, 0x5b, 0x7f511b284158, 0x7f543012d7fb, 0x7f544395bfa0 <_IO_strn_jumps>, 0x7f54437f4112 <_IO_vfprintf_internal+1826>, 0x0, 0x0, 0x1, 0x0, 0x0, 0x3000000018, 0x7f511b2841c0, 0x7f511b284100, 0x0, 0x4, 0x0, 0x7f543012d127, 0x0, 0x7f54438608e6 <__strftime_internal+2262>, 0x0, 0x2, 0x7f511b283ed0, 0x7f544395cb40 <_nl_C_LC_TIME>, 0x7f511b283cc7, 0x0, 0x0, 0x7f543012d7d0, 0x900000000, 0x7f511b2840a0, 0x7f511b284090, 0x1, 0x7f511b284248, 0x56055f2d0695, 0x7f544395bfa0 <_IO_strn_jumps>, 0x7f54437f4112 <_IO_vfprintf_internal+1826>, 0x0, 0x0, 0x0, 0x74561a00, 0x0, 0x7f5100000000, 0x7f511b283c70, 0xffffffffffffffff, 0x0, 0x1, 0x0, 0x7f53201729e4, 0x7f511b283d20, 0x7f511b284058, 0x7f5400000000, 0x0, 0x0, 0x7f544395b760 <_IO_helper_jumps>, 0xd68, 0x56055f2d0693, 0x0, 0x56055f2d0693, 0x1, 0x56055f2d0695, 0xf5, 0x7f511b2841a0, 0x7f511b284190, 0x35, 0x7f511b284348, 0x7f54300c96c8, 0x7f544395bfa0 <_IO_strn_jumps>, 0x7f54437f4112 <_IO_vfprintf_internal+1826>, 0xe10, 0x7f5320000020, 0x6, 0x6dff0, 0x0, 0x3000000018, 0x7f511b2843b0, 0x7f511b2842f0, 0x0, 0x1, 0x0, 0xe27ea02974561a00, 0x7f5200000000, 0x7f54438608e6 <__strftime_internal+2262>, 0x7f5100000000, 0x2, 0x7f511b2840c0, 0x7f544395cb40 <_nl_C_LC_TIME>, 0x7f511b283eb7, 0x0, 0xef, 0x7f54300c96bf, 0x95f36dd20, 0x7f5100000002, 0x1, 0x0, 0x7f511b283ed0, 0x56055f34c5e5 <dateformat+5>, 0x100, 0x7f511b283dc0, 0x135fb9bf80, 0x565f270815, 0x5700000057, 0xe27ea02974561a00, 0x7f511b283d70, 0x7f511b283d70, 0xff, 0x56055f2cfb47, 0x323230320020, 0xe27ea02974561a00, 0x7f532010c4a8, 0x7f5320012284, 0x7f511b283fbb, 0x100, 0x7f5443960560 <_nl_global_locale>, 0x13, 0x7f511b283fbb, 0x7f54438606ea <__strftime_internal+1754>, 0x7f532010c5a7, 0x7f5300000000, 0x7f511b2840c0, 0x7f544395cb40 <_nl_C_LC_TIME>, 0x7f511b283eb7, 0x0, 0xf5, 0x7f511b2840d4, 0x900000020, 0x7f5443925305, 0x8, 0x56055f271bf6 <timesub+1688>, 0x7f511b2840c0, 0x56055fb993c0, 0xe10, 0x7f5320000020, 0x6, 0x6dff0, 0x7f54439646f0 <__libc_multiple_threads>, 0x7f532018a010, 0x56055f36dd20 <enddata>, 0x7f54438291a2 <__libc_calloc+130>, 0x7f529c0234f8, 0x7f511b283ec0, 0x56055f36dd20 <enddata>, 0xe27ea02974561a00, 0x7f529c0c3ba2, 0x7f529c0234f8, 0x7f511b283f40, 0xe27ea02974561a00, 0x7f532001288e, 0x7f529c0234f8, 0x7f511b283f40, 0x56055f36dd20 <enddata>, 0x7f532001288e, 0x7f529c0c3ba2, 0x56055f36dd20 <enddata>, 0x56055f273586 <ast_strftime_locale+620>, 0x5fdc6736, 0x0, 0x7f511b2840c0, 0x56055f34c5e5 <dateformat+5>, 0x100, 0x7f511b283fb0, 0x135fb9bf80, 0x565f270815, 0x5700000057, 0x56055f2ebb03, 0xffffffff20112438, 0x7f5320012285, 0x7f5320012280, 0xf, 0x7f5320112438, 0x7f5320112468, 0x56055f2ebccc <__ast_string_field_empty_buffer+2>, 0x56055f294c8e <ast_get_tid+30>, 0x7f532011250a, 0x3cea0000000f, 0x7f511b284210, 0x56055f1c2623 <format_log_message_ap+2617>, 0x3, 0x56055f2cfb47, 0x7f5360004fa0, 0x7f54300c9d30 <__PRETTY_FUNCTION__.18753>, 0x7f54300c800b, 0x500000ae8...}
        num = {chan = 0x7f529c023258, busy = 0, congestion = 0, nochan = 0}
        prestart = 0
        orig = 300000
        peer = 0x0
        outgoing = 0x7f5320077a50
        single = 1
        caller_entertained = 0
        featurecode = 0x7f511b283830
        cc_recall_core_id = -1
        is_cc_recall = 0
        cc_frame_received = 0
        num_ringing = 0
        sent_ring = 0
        sent_progress = 0
        start = {tv_sec = 1608279862, tv_usec = 598246}
        __PRETTY_FUNCTION__ = "wait_for_answer"
#8  0x00007f54300c4cf4 in dial_exec_full (chan=0x7f529c023258, data=0x7f511b285a20 "PJSIP/ngcore/sip:0123456789@x.x.x.x:5060,300,Tb(ngpbx-to-proxy_pre-handler^s^1)", peerflags=0x7f511b2858b8, continue_exec=0x0) at app_dial.c:2850
        res = 0
        rest = 0x0
        cur = 0x0
        out_chans = {first = 0x7f5320077a50, last = 0x7f5320077a50}
        outgoing = 0x7f5320077a50
        tmp = 0x0
        peer = 0x56055f2844d9 <ast_threadpool_push+147>
        to = 299128
        num = {chan = 0x7f529c023258, busy = 0, congestion = 0, nochan = 0}
        cause = 0
        config = {features_caller = {flags = 0}, features_callee = {flags = 0}, start_time = {tv_sec = 0, tv_usec = 0}, nexteventts = {tv_sec = 0, tv_usec = 0}, feature_start_time = {tv_sec = 0, tv_usec = 0}, feature_timer = 0, timelimit = 0, play_warning = 0, warning_freq = 0, warning_sound = 0x0, end_sound = 0x0, start_sound = 0x0, flags = 0, end_bridge_callback = 0x0, end_bridge_callback_data = 0x0, end_bridge_callback_data_fixup = 0x0}
        calldurationlimit = {tv_sec = 0, tv_usec = 0}
        dtmfcalled = 0x0
        dtmfcalling = 0x0
        dtmf_progress = 0x0
        pa = {sentringing = 0, privdb_val = 0, privcid = '\000' <repeats 255 times>, privintro = '\000' <repeats 1023 times>, status = "NOANSWER\000GS", '\000' <repeats 244 times>}
        sentringing = 0
        moh = 0
        outbound_group = 0x0
        result = 0
        parse = 0x7f511b284540 "PJSIP"
        opermode = 0
        delprivintro = 0
        args = {argc = 3, {argv = {0x7f511b284540 "PJSIP", 0x7f511b28456f "300", 0x7f511b284573 "Tb(ngpbx-to-proxy_pre-handler,s,1", 0x0}, {peers = 0x7f511b284540 "PJSIP", timeout = 0x7f511b28456f "300", options = 0x7f511b284573 "Tb(ngpbx-to-proxy_pre-handler,s,1", url = 0x0}}}
        opts = {flags = 2199024304128}
        opt_args = {0x2 <error: Cannot access memory at address 0x2>, 0x56055f2d0695 "", 0x0, 0x7f511b285360 "", 0x7f511b285350 "", 0x2d <error: Cannot access memory at address 0x2d>, 0x0, 0x56055f2e0dc3 "'\n", 0x7f544395bfa0 <_IO_strn_jumps> "", 0x7f54437f4112 <_IO_vfprintf_internal+1826> "H\213\225H\373\377\377H\211\321L)\361H9\301\017\205\230\373\377\377\270\377\377\377\177D)\340H\230H9\301\017\217\225\375\377\377A\001̀:", 0x0, 0x0, 0x0, 0x0, 0x0, 0x3000000018 <error: Cannot access memory at address 0x3000000018>, 0x7f511b285570 "\220U(\033Q\177", 0x7f511b284576 "ngpbx-to-proxy_pre-handler,s,1", 0x0, 0x2 <error: Cannot access memory at address 0x2>}
        fulldial = 0
        num_dialed = 1
        ignore_cc = 0
        device_name = "PJSIP/ngcore\000\060\060\060\060\065\067\070\066\000\000\000\030R(\033Q\177", '\000' <repeats 26 times>, "\060\000\000\000\060\000\000\000\360W(\033Q\177\000\000\060W(\033Q\177\000"
        forced_clid_name = "`W(\033Q\177\000\000\240V(\033Q\177\000\000\000\000\000\000\000\000\000\000I\373,_\005V", '\000' <repeats 18 times>, "\060N(\033Q\177\000\000\377\377\377\377\377\377\377\377\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000"
        stored_clid_name = "\000\000\000\000\000\000\000\000G\373,_\005V\000\000\000\000\000\000\000\000\000\000\310J\002 S\177\000\000\000\000\000\000Q\177\000\000\212\377\377\377", '\000' <repeats 12 times>, "`\267\225CT\177\000\000h\r\000\000\000\000\000\000\060\000\000\000\060\000\000"
        force_forwards_only = 0
        forced_clid = {name = {str = 0x0, char_set = 1, presentation = 0, valid = 0 '\000'}, number = {str = 0x0, plan = 0, presentation = 1, valid = 0 '\000'}, subaddress = {str = 0x0, type = 0, odd_even_indicator = 0 '\000', valid = 0 '\000'}, tag = 0x0}
        stored_clid = {name = {str = 0x0, char_set = 1, presentation = 0, valid = 0 '\000'}, number = {str = 0x7f511b284520 "0123456789", plan = 0, presentation = 0, valid = 1 '\001'}, subaddress = {str = 0x0, type = 0, odd_even_indicator = 0 '\000', valid = 0 '\000'}, tag = 0x0}
        caller = {id = {name = {str = 0x0, char_set = 1, presentation = 0, valid = 0 '\000'}, number = {str = 0x7f511b284520 "0123456789", plan = 0, presentation = 0, valid = 1 '\001'}, subaddress = {str = 0x0, type = 0, odd_even_indicator = 0 '\000', valid = 0 '\000'}, tag = 0x0}, ani = {name = {str = 0x0, char_set = 1, presentation = 0, valid = 0 '\000'}, number = {str = 0x0, plan = 0, presentation = 0, valid = 0 '\000'}, subaddress = {str = 0x0, type = 0, odd_even_indicator = 0 '\000', valid = 0 '\000'}, tag = 0x0}, priv = {name = {str = 0x0, char_set = 1, presentation = 0, valid = 0 '\000'}, number = {str = 0x0, plan = 0, presentation = 0, valid = 0 '\000'}, subaddress = {str = 0x0, type = 0, odd_even_indicator = 0 '\000', valid = 0 '\000'}, tag = 0x0}, ani2 = 0}
        max_forwards = 20
        __PRETTY_FUNCTION__ = "dial_exec_full"
#9  0x00007f54300c736c in dial_exec (chan=0x7f529c023258, data=0x7f511b285a20 "PJSIP/ngcore/sip:0123456789@x.x.x.x:5060,300,Tb(ngpbx-to-proxy_pre-handler^s^1)") at app_dial.c:3336
        peerflags = {flags = 0}
#10 0x000056055f20e58b in pbx_exec (c=0x7f529c023258, app=0x56056156f2f0, data=0x7f511b285a20 "PJSIP/ngcore/sip:0123456789@x.x.x.x:5060,300,Tb(ngpbx-to-proxy_pre-handler^s^1)") at pbx_app.c:494
        res = 22021
        u = 0x7f5320066100
        saved_c_appl = 0x0
        saved_c_data = 0x0
        __PRETTY_FUNCTION__ = "pbx_exec"
#11 0x000056055f1fb3da in pbx_extension_helper (c=0x7f529c023258, con=0x0, context=0x7f529c023c10 "ngpbx-to-proxy02-pjsip", exten=0x7f529c023c60 "0123456789", priority=4, label=0x0, callerid=0x7f529c004c50 "045162029", action=E_SPAWN, found=0x7f511b288cc4, combined_find_spawn=1) at pbx.c:2907
        e = 0x7f5150dc5780
        app = 0x56056156f2f0
        substitute = 0x7f511b285940 "PJSIP/ngcore/sip:${DIALNUMBER}@x.x.x.x:5060,${PSTN_DIAL_TIME},${PSTN_DIAL_OPTIONS}b(ngpbx-to-proxy_pre-handler^s^1)"
        q = {incstack = {0x0 <repeats 512 times>}, stacklen = 0, status = 5, swo = 0x0, data = 0x0, foundcontext = 0x7f529c023c10 "ngpbx-to-proxy02-pjsip"}
        passdata = "PJSIP/ngcore/sip:0123456789@x.x.x.x:5060,300,Tb(ngpbx-to-proxy_pre-handler^s^1)\000LLERID(num): 2024\000\063\066\061\067\063\061\070\060,u_pbx_server_id: 168,u_guid: ea610ae290e6346bf6dd531e1e42be7d46db1591)\000ae86b6fefe1c68b)"...
        matching_action = 0
        __PRETTY_FUNCTION__ = "pbx_extension_helper"
#12 0x000056055f1febd7 in ast_spawn_extension (c=0x7f529c023258, context=0x7f529c023c10 "ngpbx-to-proxy02-pjsip", exten=0x7f529c023c60 "0123456789", priority=4, callerid=0x7f529c004c50 "045162029", found=0x7f511b288cc4, combined_find_spawn=1) at pbx.c:4160
No locals.
#13 0x000056055f1ff915 in __ast_pbx_run (c=0x7f529c023258, args=0x0) at pbx.c:4337
        digit = 0
        invalid = 0
        timeout = 0
        dst_exten = "\000#\027 S\177\000\000\061\000\000\000\001\000\000\000\260\213(\033Q\177\000\000\022\333\033_\005V\000\000\061\000\000\000\000\000\000\000`&\n\024S\177\000\000\020\214(\033Q\177\000\000\252=\034_\005V\000\000X#\027 S\177\000\000w=\034_\005V\000\000\v\002\000\000\377\377\377\377\331E\016 S\177\000\000`&\n\024S\177\000\000`z\203\237S\177\000\000\002\000\000\000\032\003\000\000\v`\203\237S\177\000\000\003\000\000\000\004\000\000\000P&\n\024S\177\000\000 \214(\033\377\377\377\377X&\n\024S\177\000\000Ќ(\033Q\177\000\000\031\n\r_\005V\000\000\370{*_\005V\000\000{y*_\005V\000\000\v\002\000\000\377\377\377\377`"...
        pos = 0
        found = 1
        res = 0
        autoloopflag = 0
        error = 0
        pbx = 0x7f5320025270
        callid = 0x0
        __PRETTY_FUNCTION__ = "__ast_pbx_run"
#14 0x000056055f20117d in pbx_thread (data=0x7f529c023258) at pbx.c:4661
        c = 0x7f529c023258
#15 0x000056055f291cdf in dummy_start (data=0x7f536000f1f0) at utils.c:1239
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {0, 7617877189439841998, 139997105940478, 139997105940479, 139986324723456, 139999626680864, 7617877189481785038, 4256089606090974926}, __mask_was_saved = 0}}, __pad = {0x7f511b288ed0, 0x0, 0xe27ea02974561a00, 0x0}}
        __cancel_routine = 0x56055f0c56e1 <ast_unregister_thread>
        __cancel_arg = 0x7f511b289700
        __not_first_call = 0
        ret = 0x7f5434045a20
        a = {start_routine = 0x56055f201158 <pbx_thread>, data = 0x7f529c023258, name = 0x7f5360011e00 "pbx_thread", ' ' <repeats 11 times>, "started at [ 4687] pbx.c ast_pbx_start()"}
#16 0x00007f5443e09fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139986324723456, -7558706345709607218, 139997105940478, 139997105940479, 139986324723456, 139999626680864, 7617877189454522062, 7616311966418527950}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#17 0x00007f544389d4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.```

**Comment by dkgroot** [comment]
Hi Niklas,
I have been working on this exact problem for the last three weeks and we finally had a break through earlier this week. 

***Git***
_Checkout this temporary branch_
```
cd /usr/src/chan-sccp
git fetch origin
git branch issues/segfault origin/issues/segfault
git checkout issues/segfault
git pull
./configure [....]
make -j4 && make install && make reload
```

_move back to develop afterwards:_
```
cd /usr/src/chan-sccp
git checkout develop
git pull
./configure [....]
make -j4 && make install && make reload
```

That should fix the issue. Please let me know if there are any side effects etc. It is a problem that seem to be very sporadic and takes the other company that reported it earlier about 5-10.000 calls to reproduce.

The problem was made aware to me by @tomgilabert.

Regards,
Diederik

**Comment by dkgroot** [comment]
@pnlarsson 
In regard of the seriousness and testing already done, i have decided to merge the changes into the develop branch. This will be done a couple of minutes from now. So the issues/segfault branch will be discontinued. You will only have to pull latest develop revision.
